### ISSUE TITLE
clustering

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI-dev#14]
To start, maybe figure out when VaDE does/doesn't work.

https://arxiv.org/pdf/1611.05148.pdf

**Comment by maxime1310** [comment]
@jeff-regier I'll just clean the code and make sure it's able to find the right clusters with the Retina dataset (for now it runs fine on Cortex), and then I'll do this so we can close the issue!

**Comment by maxime1310** [comment]
@jeff-regier the code I just pushed should:
-reproduce Romain's visual clustering on the Retina dataset
-show if using a VADE with those pre-trained weights yields improvement in the clustering (haven't included clustering metrics yet, the appreciation is simply visual for the moment)
I launched it for the same number of epochs as Romain did (it takes a bit of time as the dataset is huge), once I have satisfying visual clustering results I'll push it and close the issue.

**Comment by jeff-regier** [comment]
Sounds good, thanks Maxime.

**Comment by maxime1310** [comment]
The VADE doesn't improves much the clustering metrics used in the paper (i.e ARI, NMI, silhouette score) on the Retina dataset, but on the other hand (interesting fact considering the desperate need for pretraining on MNIST) seems to also work without much pretraining.

After pretraining:
![after pretraining](https://user-images.githubusercontent.com/26231992/39204378-7c693138-47ac-11e8-94a3-be7af3eb20ce.png)

After VADE:
![after vade](https://user-images.githubusercontent.com/26231992/39204418-9212ca62-47ac-11e8-8065-ecae82fa2dae.png)

**Comment by jeff-regier** [comment]
Very interesting. Even though there's no obvious improvement for VADE, it could just be that this dataset is too easy to cluster (and that the few mistakes we see are essentially impossible to correct). Might be good to revisit VADE if we need to improve visualization in the future.

**Comment by maxime1310** [comment]
I definitely agree with you. Perhaps I'll take a bit of time to run it on datasets where scVI performs less well for clustering to see if there is improvement.
