### ISSUE TITLE
MMD-regularized autoencoders

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI-dev#32]
@Edouard360 You maybe interested in trying something like WAE-MMD or InfoVAE w/MMD if you're going to work on improving the variational distribution.

https://arxiv.org/pdf/1711.01558.pdf
https://arxiv.org/pdf/1706.02262.pdf

**Comment by Edouard360** [comment]
Thank you very much ! I'll look into it !

**Comment by jeff-regier** [comment]
Actually, I now think important-weighted autoencoders (#8) are a more straightforward way to improve the quality of our variational distribution.
