### ISSUE TITLE
Flake8 problem

### ISSUE THREAD

**Issue by Edouard360** [YosefLab/scVI-dev#37]
https://github.com/YosefLab/scVI-dev/blob/784b2b3fe90764c7cd8dfd1c54f0f8e763cc5ca5/Makefile#L52-L54

Makefile doesn't take into account ./run_benchmarks.py in the flake8 command, so we sometimes push we unformatted code, and the build fails. Can we jsut add ./run_benchmarks.py in Makefile ?

**Comment by jeff-regier** [comment]
Sure, that's a good idea.

Or, if you delete `scvi tests` from that line, it could work too. I think then it runs on all the python code in the directory.
