### ISSUE TITLE
.h5 for Cortex / sparsity as default format

### ISSUE THREAD

**Issue by Edouard360** [YosefLab/scVI-dev#62]
We are still saving cortex data as a .npy file and separate labels from X from genes_names, ect...

Maybe the output of preprocessing should always be a .h5 file saved to disk ?

**Comment by jeff-regier** [comment]
Does preprocessing take less than, say, 15 seconds? If so, it's probably better not to write the preprocessed results to disk at all. Better to avoid one more file format. Just preprocess the raw data every time you need it to use it.

**Comment by Edouard360** [comment]
Yes ok I will time that
