### ISSUE TITLE
unit test of brain_large.py

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI-dev#64]
http://cf.10xgenomics.com/samples/cell-exp/2.1.0/neurons_900/neurons_900_molecule_info.h5

I think it has the same format as `brain_large`, but it's < 100 MB. (Both are from 10x.) If the formats are the same, it could work well for a unit test of the `brain_large.py` code.

**Comment by Edouard360** [comment]
It doesn't exactly work, and throws:

    Exception: Genome mm10 does not exist in this file.

It fails at the statement:

    f.walk_nodes('/' + genome, 'Array')

So I did:

    f.list_nodes('/','Array')

And looked at the structure of the `neurons_900_molecule_info.h5`, and some fields are the same but not all of them. In particular the keys dsets['data'], dsets['indices'], dsets['indptr'] and dsets['shape'] are nowhere to be found

**Comment by Edouard360** [comment]
Now I come to think that we could make available (on a aws server for instance), a very small manually subsampled version of the `brain_large` dataset, just for the sake of these unit tests ?

**Comment by jeff-regier** [comment]
Yes, I think that's the way to go. The only issue is where to host it. It's supposedly bad practice to store data---even test data--in a git repo. On the other hand, if we made the test data for each dataset very small, maybe it wouldn't be so bad. And it would be very convenient not to depend on another server.

**Comment by jeff-regier** [comment]
Do you think you could test brain_large with, say, < 50 KB of data? If so, how about checking the test data into `test/data`?
