### ISSUE TITLE
Quick question - Should I use this or the TensorFlow version?

### ISSUE THREAD

**Issue by vals** [YosefLab/scVI-dev#68]
Hi,

I liked the paper, and wanted to run scVI on a bunch of data, and encountered this repo.

Is this version in working order, or should I use the TensorFlow version until you announce this is done or so?

/Valentine

**Comment by jeff-regier** [comment]
Hi Valentine, Thanks for your interest in scVI. It's probably better to use the tensorflow version for now, unless you're familiar with PyTorch and don't mind digging through the code to make it work for your dataset. This version should be ready in a month or so.

**Comment by vals** [comment]
Thanks!
