### ISSUE TITLE
early stopping

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI-dev#70]
Lets stop the training procedure once the objective function isn't changing much, even if the max number of epochs hasn't been reached yet. 

See

http://www.nxn.se/valent/2018/4/20/count-based-autoencoders-and-the-future-for-scrna-seq-analysis

**Comment by romain-lopez** [comment]
This is an important issue. Either a cross-validation early stopping can be used or a convergence criterion as Jeff suggests (when the loss does not change relatively to a certain threshold).
