### ISSUE TITLE
upgrade to pytorch 0.4

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI-dev#72]
PyTorch 0.4 has a `lgamma` function, so we won't have to use `cffi` any more to compile our own. We should upgrade to 0.4 as soon as it's released. See

https://github.com/pytorch/pytorch/issues/5673

**Comment by soumith** [comment]
if you want `no_grad` everywhere except the training loop, it's better to set it globally. `torch.set_grad_enabled(False)`, and within training loop, do `with torch.set_grad_enabled(True):`.

See: http://pytorch.org/docs/stable/autograd.html#torch.autograd.set_grad_enabled

**Comment by jeff-regier** [comment]
Thanks for the tip! We all really appreciate your work on pytorch.
