### ISSUE TITLE
move project from YosefLab/scVI-dev repo to YosefLab/scVI

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI-dev#76]
Minimally, we need to finish #50 before replacing the old tensorflow code (perhaps moving the tensorflow code to the scVI-reproducibility repository).

**Comment by romain-lopez** [comment]
I pushed the code from YosefLab/scVI to romain-lopez/scVI-reproducibility/demo_code. 
Please go ahead when ready and link in the new YosefLab/scVI to the old tensorflow version for reference.
